name: git version

on:
  push:
    branches:
      - main

jobs:
  codacy-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@v4
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        upload: true
        gh-code-scanning-compat: true

  semver-bump:
    needs: codacy-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures tags are fetched

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          create_annotated_tag: true
          custom_tag: ${{ github.event.head_commit.message }}
        id: tagging

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          release_name: Release ${{ steps.tagging.outputs.new_tag }}
          body: |
            Changes in this Release:
            - ${{ github.event.head_commit.message }}
